# IMPORTANT: Reset this value with a secret only you know.
# python3 -c 'import secrets; print(secrets.token_hex())'
SECRET_KEY="dev"

SAML_PATH="space_trace/saml"
SQLALCHEMY_DATABASE_URI="sqlite:///../instance/trace.db"
SQLALCHEMY_TRACK_MODIFICATIONS=false